src/cart/urls.py
from django.conf.urls import url
from . import views

app_name = 'cart'

urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

src/ecomm/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url, include
from django.contrib import admin

from profiles import views as profiles_views
from contact import views as contact_views
from checkout import views as checkout_views
#from shop import views as product_views
#from shopping_cart import views as cart_views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', profiles_views.home, name='home'),
    url(r'^about/$', profiles_views.about, name='about'),
    url(r'^profile/$', profiles_views.userProfile, name='profile'),
    url(r'^contact/$', contact_views.contact, name='contact'),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^checkout/', include('checkout.urls')),
    url(r'^shop/', include('shop.urls')),
    url(r'^cart/', include('cart.urls')),
    url(r'^orders/', include('orders.urls')),
]

if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/shop/urls.py
from django.conf.urls import url
from . import views

app_name = 'shop'

urlpatterns = [
    url(r'^$', views.product_list, name='product_list'),
    url(r'^(?P<category_slug>[-\w]+)/$', views.product_list, name='product_list_by_category'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.product_detail, name='product_detail'),
]

src/profiles/models.py
from django.conf import settings
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

# Create your models here.

class profile(models.Model):
    name = models.CharField(max_length=120)
    description = models.TextField(default='description default value')
    #location = models.CharField(max_length=120,default='my location default',blank=True,null=True)
    #job = models.CharField(max_length=120,null=True)

    def __unicode__(self):
        return self.name

src/profiles/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from allauth.account.forms import SignupForm


# Create your views here.
def home(request):
    #context=locals() ----> puts everything in each view's context so we don't prefer using locals. The lack of specificity is the major drawback while using locals.
    context={}
    template='home.html'
    return render(request,template,context)

def about(request):
    context={}
    template='about.html'
    return render(request,template,context)

@login_required
def userProfile(request):
    user = request.user
    context={'user':user}
    template='profile.html'
    return render(request,template,context)

src/profiles/templates/about.html
{% extends 'base.html' %}

{% block content %}
<h1>About ZenStore</h1>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Fermentum posuere urna nec tincidunt praesent semper feugiat nibh. Malesuada nunc vel risus commodo viverra maecenas. Sed turpis tincidunt id aliquet risus feugiat in. Lorem donec massa sapien faucibus et molestie ac. Orci ac auctor augue mauris. Tincidunt eget nullam non nisi est sit amet. Sociis natoque penatibus et magnis dis parturient montes nascetur. Tincidunt praesent semper feugiat nibh. Vitae semper quis lectus nulla at volutpat diam. Lacus sed turpis tincidunt id aliquet risus feugiat. Commodo quis imperdiet massa tincidunt. Fringilla urna porttitor rhoncus dolor.

Mauris ultrices eros in cursus turpis massa tincidunt. At lectus urna duis convallis convallis tellus id interdum. Auctor eu augue ut lectus arcu bibendum at varius. Risus sed vulputate odio ut enim blandit. Tristique senectus et netus et malesuada fames ac. Ut ornare lectus sit amet. At risus viverra adipiscing at in tellus integer. Pharetra diam sit amet nisl suscipit adipiscing bibendum. Augue eget arcu dictum varius duis. Nisl vel pretium lectus quam id leo in vitae. Purus sit amet volutpat consequat mauris nunc. At erat pellentesque adipiscing commodo elit at imperdiet. Sed enim ut sem viverra aliquet eget. Nunc congue nisi vitae suscipit. Diam vel quam elementum pulvinar.

Enim neque volutpat ac tincidunt vitae. Nulla facilisi morbi tempus iaculis urna id volutpat lacus. Turpis egestas pretium aenean pharetra magna ac placerat. Feugiat nibh sed pulvinar proin gravida hendrerit lectus a. Fermentum dui faucibus in ornare quam viverra orci sagittis. Proin nibh nisl condimentum id venenatis a condimentum vitae sapien. Sed faucibus turpis in eu. Cursus eget nunc scelerisque viverra mauris in aliquam sem. Nunc faucibus a pellentesque sit amet porttitor eget. Facilisi nullam vehicula ipsum a.

Nisl nisi scelerisque eu ultrices vitae auctor. Egestas diam in arcu cursus euismod quis viverra nibh cras. Gravida in fermentum et sollicitudin ac orci phasellus. Diam vel quam elementum pulvinar etiam non quam lacus suspendisse. Amet nisl purus in mollis nunc. Gravida rutrum quisque non tellus orci ac. Et tortor at risus viverra adipiscing at in tellus integer. Mi ipsum faucibus vitae aliquet nec ullamcorper sit amet. Feugiat scelerisque varius morbi enim nunc. Aenean sed adipiscing diam donec adipiscing tristique risus.</p>
{% endblock %}

src/profiles/templates/base.html
{% load staticfiles %}

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <title>{% block title %}ZenStore{% endblock %}</title>
    <link rel="icon" type="image/ico" href="favicon.ico" />

    <!-- Bootstrap core CSS -->
<link href="{%static 'css/bootstrap.min.css'%}" rel="stylesheet" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <!-- Custom styles for this template -->
    <link href="{%static 'css/jumbotron.css'%}" rel="stylesheet">
    <link href="{%static 'css/main.css'%}" rel="stylesheet"/>
  </head>
  <body>

{%include 'navbar.html'%}
<main role="main">
  <div class="container" style="padding-top:50px;">
  {% block content %}
  {% endblock %}

  {% block styles %}
  {% endblock %}

  {% block contact %}
  {% endblock %}
</div>

  {% block content2 %}
  {% endblock %}

</main>



<footer class="container" style="text-align:right;"">
  <p>&copy; Company 2017-2018</p>
</footer>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
      <script>window.jQuery || document.write('<script src="/docs/4.2/assets/js/vendor/jquery-slim.min.js"><\/script>')</script><script src="{%static 'javascript/bootstrap.bundle.min.js'%}" integrity="sha384-zDnhMsjVZfS3hiP7oCBRmfjkQC4fzxVxFhBx8Hkz2aZX8gEvA/jsP3eXRCvzTofP" crossorigin="anonymous"></script>
      <script type="text/javascript" src="https://js.stripe.com/v3/"></script>
      {% block script %}
      {% endblock %}

      <script>
        $(document).ready(function(){
          {% block jquery %}
          {% endblock %}
        });
      </script>
    </body>
</html>

src/profiles/templates/home.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block styles %}
<style>
  .jumbotron{
    text-align:center;
  }
  </style>
{% endblock %}



{% block content %}
<div class="jumbotron">

  <div class="container">
    <h1 class="display-3">Welcome to ZenStore!</h1>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Arcu ac tortor dignissim convallis aenean et. Ac feugiat sed lectus vestibulum mattis ullamcorper velit sed ullamcorper. Enim praesent elementum facilisis leo vel. Est pellentesque elit ullamcorper dignissim cras tincidunt lobortis. Sed id semper risus in hendrerit. Tempus imperdiet nulla malesuada pellentesque. </p>
    <p><a class="btn btn-primary btn-lg" href="{% url 'shop:product_list' %}" role="button">Shop &raquo;</a></p>
  </div>

</div>
{% endblock %}


{% block content2 %}
<div class="container">
    <!-- Example row of columns -->
    <div class="row">
      <div class="col-md-8">
        <a href="#"><img src="{% static 'img/home1.jpeg' %}" class="img-responsive"></img></a>
      </div>
      <div class="col-md-4">
        {% if request.user.is_authenticated %}
          <h3>Hello {{ request.user }}</h3>
        {% else %}
          <form class="login" method="POST" action="{%url 'account_login'%}">
          {% csrf_token %}


          <div id="div_id_login" class="form-group"> <label for="id_login" class="control-label  requiredField">
          Login<span class="asteriskField">*</span> </label> <div class="controls "> <input type="text" name="login" placeholder="Username or e-mail" autofocus="autofocus" class="textinput textInput form-control" required="" id="id_login"> </div> </div> <div id="div_id_password" class="form-group"> <label for="id_password" class="control-label  requiredField">
          Password<span class="asteriskField">*</span> </label> <div class="controls "> <input type="password" name="password" placeholder="Password" class="textinput textInput form-control" required="" id="id_password"> </div> </div> <div class="form-group"> <div id="div_id_remember" class="checkbox"> <label for="id_remember" class=""> <input type="checkbox" name="remember" class="checkboxinput" id="id_remember">
          Remember Me
          </label> </div> </div>

          <a class="btn btn-link button secondaryAction" href="{% url 'account_reset_password' %}">Forgot Password?</a>
          <a class="btn btn-link button secondaryAction" href="{%url 'account_signup'%}">Sign Up</a>
          <button class="btn-outline-dark primaryAction" type="submit">Sign In</button>
          </form>
        {% endif %}

      </div>
    </div>

    <hr>

  </div>
{% endblock %}

src/profiles/templates/navbar.html
{% load staticfiles %}
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
<a class="navbar-brand" href="{%url 'home'%}"><img></img>ZenStore</a>
<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
<span class="navbar-toggler-icon"></span>
</button>

<div class="collapse navbar-collapse" id="navbarsExampleDefault">
<ul class="navbar-nav mr-auto">
  {% url 'home' as home %}
  {% url 'about' as about %}
  {% url 'contact' as contact %}
  <li {% if request.path == home %} class="nav-item active" {% endif %} class="nav-item">
    <a class="nav-link" href="{%url 'home'%}">Home <span class="sr-only">(current)</span></a>
  </li>
  <li {% if request.path == about %} class="nav-item active" {% endif %} class="nav-item">
    <a class="nav-link" href="{%url 'about'%}">About</a>
  </li>
  <li {% if request.path == contact %} class="nav-item active" {% endif %} class="nav-item">
    <a class="nav-link" href="{%url 'contact'%}">Contact</a>
  </li>
  <li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Account</a>
    <div class="dropdown-menu" aria-labelledby="dropdown01">
      {% if not request.user.is_authenticated %}
        <a class="dropdown-item" href="{%url 'account_login'%}">Login</a>
        <a class="dropdown-item" href="{%url 'account_signup'%}">Sign Up</a>
      {% else %}
        <a class="dropdown-item" href="{%url 'account_logout'%}">Logout</a>
      {% endif %}
    </div>
  </li>
</ul>
<button class="btn btn-secondary btn-lg" style="position:fixed;right:12px;top:4px;" onclick="{% url 'cart:cart_detail'%}">
            {% with total_items=cart|length %}
                {% if cart|length > 0 %}
                    My Shopping Order :
                    <a href="{% url 'cart:cart_detail' %}" style="color: #ffffff">
                        {{ total_items }} item{{ total_items|pluralize }}, &#8377; {{ cart.get_total_price }}
                    </a>
                    {% else %}
                    Your cart is empty.
                {% endif %}
            {% endwith %}
  </button>
</div>
</nav>

src/profiles/templates/profile.html
{% extends 'base.html' %}

{% block content %}
{{ user.username }}
{{ user.email }}
{% endblock %}